### ISSUE TITLE
The `add-path` command is disabled

### ISSUE THREAD

**Issue by andrioid** [chrisdickinson/setup-yq#2]
My workflows stopped working today. Can we update to adhere to the new ENV rules?

```
Error: Unable to process command '::add-path::/opt/hostedtoolcache/yq/3.3.2/x64' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by andrioid** [comment]
Still not working. Did we forget to run the build step? The `dist/` directory hasn't been updated in 11 months.

**Comment by missedone** [comment]
@andrioid , could you create a new tag `1.0.1` for the fix? though use `latest` works for me

**Comment by andre-lx** [comment]
not fixed. only works with latest. please update your release. thanks

**Comment by andrioid** [comment]
@missedone: I don't have access to do that. @chrisdickinson needs to do it.
